/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gyma;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author JOBS
 */
public class add_pack extends javax.swing.JFrame {

    /**
     * Creates new form add_pack
     */
    public add_pack() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        plname = new javax.swing.JLabel();
        pldur = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        pdur = new javax.swing.JTextField();
        daily = new javax.swing.JTextField();
        mothly = new javax.swing.JTextField();
        tmonth = new javax.swing.JTextField();
        pful = new javax.swing.JTextField();
        pid = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        del = new javax.swing.JButton();
        smonth = new javax.swing.JTextField();
        A = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        e = new javax.swing.JLabel();
        cho = new javax.swing.JComboBox<>();
        up = new javax.swing.JButton();
        tmonth1 = new javax.swing.JTextField();
        smonth1 = new javax.swing.JTextField();
        pful1 = new javax.swing.JTextField();
        mothly1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        con = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 100, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("        Package");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 330, 130));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Package ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 150, 60));

        plname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        plname.setText("Package Name");
        jPanel1.add(plname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 180, 60));

        pldur.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pldur.setText("Package Duration");
        jPanel1.add(pldur, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 220, 60));

        pname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 200, -1));

        pdur.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(pdur, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 200, -1));

        daily.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(daily, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 330, 130, -1));

        mothly.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(mothly, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 380, 130, -1));

        tmonth.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(tmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 430, 130, -1));

        pful.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(pful, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 540, 130, 40));

        pid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 200, -1));

        add.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add.setText("Add Package");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, 240, 60));

        del.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        del.setText("Delete Package");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel1.add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, 240, 60));

        smonth.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(smonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 480, 130, -1));

        A.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        A.setText("Daily");
        jPanel1.add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 310, 80, 60));

        b.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b.setText("Monthly");
        jPanel1.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 100, 60));

        c.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        c.setText("3 Months");
        jPanel1.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, 120, 60));

        d.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        d.setText("6 Months");
        jPanel1.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 470, 120, 60));

        e.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        e.setText("Full");
        jPanel1.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 540, 60, 40));

        cho.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADD  PACKAGE", "UPDATE PACKAGE", "DELETE PACKAGE" }));
        cho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choActionPerformed(evt);
            }
        });
        jPanel1.add(cho, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 240, 60));

        up.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        up.setText("Update Package");
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        jPanel1.add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, 240, 60));

        tmonth1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(tmonth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 430, 70, -1));

        smonth1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(smonth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 480, 70, -1));

        pful1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(pful1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 540, 70, 40));

        mothly1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(mothly1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 380, 70, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JOBS\\Documents\\gyma\\src\\images\\Favorites\\icons8-home-50.png")); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1163, 30, 110, 40));

        con.setIcon(new javax.swing.ImageIcon("C:\\Users\\JOBS\\Documents\\gyma\\src\\images\\pack.jpeg")); // NOI18N
        con.setText("con");
        jPanel1.add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed

        String ch=(String) cho.getSelectedItem();
        String id=pid.getText();
        String uname="root";
       String pass="jobs";
        
       String con="jdbc:Mysql://localhost:3306/gym";
       Connection conn = null;       
      
           try {
           
               
            conn=DriverManager.getConnection(con,uname,pass);
            Statement stmt=(Statement) conn.createStatement();  
            stmt.executeUpdate("DELETE FROM package where pack_id='"+id+"'");
            JOptionPane.showMessageDialog(null, "Package Deleted successfully","MESSAGE", JOptionPane.INFORMATION_MESSAGE);
           } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "error","MESSAGE", JOptionPane.INFORMATION_MESSAGE);
           
    }
    }//GEN-LAST:event_delActionPerformed

    private void choActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choActionPerformed

        String a=(String) cho.getSelectedItem();
        if(a.equals("DELETE PACKAGE")){
            del.setVisible(true);
              up.setVisible(false);
             add.setVisible(false);
            plname.setText("");
            
            pldur.setText("");
            A.setText("");
            b.setText("");
            c.setText("");
            d.setText("");
            e.setText("");
           /* f.setText("");
            h.setText("");
            g.setText("");
            i.setText("");
            j.setText("");*/
            
            pname.setVisible(false);
            pdur.setVisible(false);
            daily.setVisible(false);
            mothly.setVisible(false);
            tmonth.setVisible(false);
            smonth.setVisible(false);
            pful.setVisible(false);
              
            
            
            
        }else if(a.equals("UPDATE PACKAGE")){
             plname.setText("Package Name");
             up.setVisible(true);
             add.setVisible(false);
             del.setVisible(false);
            pldur.setText("Package Duration");
            
            A.setText("Daily");
            b.setText("Monthly");
            c.setText("3 Months");
            d.setText("6 Months");
          /*  e.setText("Full");
            f.setText("ETB.");
            h.setText("ETB.");
            g.setText("ETB.");
            i.setText("ETB.");
            j.setText("ETB.");*/
                pname.setVisible(true);
            pdur.setVisible(true);
            daily.setVisible(true);
            mothly.setVisible(true);
            tmonth.setVisible(true);
            smonth.setVisible(true);
            pful.setVisible(true);
              
            
        }else {
            
            up.setVisible(false);
             del.setVisible(false);
             add.setVisible(true);
                plname.setText("Package Name");
            pldur.setText("Package Duration");
            A.setText("Daily");
            b.setText("Monthly");
            c.setText("3 Months");
            d.setText("6 Months");
            e.setText("Full");
         /*   f.setText("ETB.");
            h.setText("ETB.");
            g.setText("ETB.");
            i.setText("ETB.");
            j.setText("ETB.");*/
                pname.setVisible(true);
            pdur.setVisible(true);
            daily.setVisible(true);
            mothly.setVisible(true);
            tmonth.setVisible(true);
            smonth.setVisible(true);
            pful.setVisible(true);
              
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_choActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
  
          String ch=(String) cho.getSelectedItem();
        String id=pid.getText();
        String a=pname.getText();
        String d=pdur.getText();
        Double da=Double.parseDouble(daily.getText());
        Double m=Double.parseDouble(mothly.getText());
        Double tm=Double.parseDouble(tmonth.getText());
        Double sm=Double.parseDouble(smonth.getText());
        Double pf=Double.parseDouble(pful.getText());
        String uname="root";
       String pass="jobs";
        
       String con="jdbc:Mysql://localhost:3306/gym";
       Connection conn = null;       
  try {
            conn=DriverManager.getConnection(con,uname,pass);
            Statement stmt=(Statement) conn.createStatement();  
            stmt.executeUpdate("insert into package "+" values('"+id+"','"+a+"','"+d+"','"+da+"','"+m+"','"+tm+"','"+sm+"','"+pf+"')");
             JOptionPane.showMessageDialog(null, "Package Added successfully","MESSAGE", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "error","MESSAGE", JOptionPane.INFORMATION_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed

             String ch=(String) cho.getSelectedItem();
        String id=pid.getText();
        String a=pname.getText();
        String d=pdur.getText();
        Double da=Double.parseDouble(daily.getText());
        Double m=Double.parseDouble(mothly.getText());
        Double tm=Double.parseDouble(tmonth.getText());
        Double sm=Double.parseDouble(smonth.getText());
        Double pf=Double.parseDouble(pful.getText());
        String uname="root";
       String pass="jobs";
        
       String con="jdbc:Mysql://localhost:3306/gym";
       Connection conn = null;       
  try {
            conn=DriverManager.getConnection(con,uname,pass);
            Statement stmt=(Statement) conn.createStatement();
            stmt.executeUpdate("UPDATE package SET pack_name='"+pname+"',pack_dur='"+pdur+"',daily_price='"+da+"',monthly_price='"+m+"' ,3_month_price='"+tm+"',6_month_price='"+sm+"',Full='"+pf+"'  WHERE pack_id ='"+pid+"'");
            JOptionPane.showMessageDialog(null, "Package Upddated successfully","MESSAGE", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "error","MESSAGE", JOptionPane.INFORMATION_MESSAGE);
        }        // TODO add your handl
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_upActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new menu().setVisible(true);
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_pack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_pack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_pack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_pack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_pack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JButton add;
    private javax.swing.JLabel b;
    private javax.swing.JLabel c;
    private javax.swing.JComboBox<String> cho;
    private javax.swing.JLabel con;
    private javax.swing.JLabel d;
    private javax.swing.JTextField daily;
    private javax.swing.JButton del;
    private javax.swing.JLabel e;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mothly;
    private javax.swing.JTextField mothly1;
    private javax.swing.JTextField pdur;
    private javax.swing.JTextField pful;
    private javax.swing.JTextField pful1;
    private javax.swing.JTextField pid;
    private javax.swing.JLabel pldur;
    private javax.swing.JLabel plname;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField smonth;
    private javax.swing.JTextField smonth1;
    private javax.swing.JTextField tmonth;
    private javax.swing.JTextField tmonth1;
    private javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables
}
