/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gyma;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.print.attribute.Size2DSyntax.MM;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static javax.swing.text.html.HTML.Tag.DD;

/**
 *
 * @author JOBS
 */
public class manegemp extends javax.swing.JFrame {

    public manegemp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ids = new javax.swing.JTextField();
        am = new javax.swing.JTextField();
        ac = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        re = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        re1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        ch = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 100, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ids.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(ids, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 233, 42));

        am.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(am, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 233, 42));

        ac.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 233, 42));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Account No.");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 120, 42));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Amount");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 90, 42));

        re.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        re.setText("Recharge");
        re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reActionPerformed(evt);
            }
        });
        jPanel2.add(re, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 130, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Trainer ID");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 102, 42));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Recharge  Balance");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 250, 42));

        re1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        re1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JOBS\\Documents\\gyma\\src\\images\\Favorites\\icons8-home-50.png")); // NOI18N
        re1.setContentAreaFilled(false);
        re1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re1ActionPerformed(evt);
            }
        });
        jPanel2.add(re1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 720));

        table.setBackground(new java.awt.Color(204, 204, 204));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trainer ID", "Trainer Name", "Sex", "Payment Day", "Type"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 840, 390));

        ch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Regular", "Shift" }));
        ch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chActionPerformed(evt);
            }
        });
        jPanel1.add(ch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 280, 180, 40));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 720));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText(">>");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 30, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reActionPerformed
       String a=ids.getText();

       DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
	LocalDate localDate = LocalDate.now();
        String y=dtf.format(localDate);
       String uname="root";
       String pass="jobs";
       String con="jdbc:Mysql://localhost:3306/gym";
       Connection  conn=null;
        try {
            conn=DriverManager.getConnection(con,uname,pass);
            Statement stmt=(Statement) conn.createStatement();
            stmt.executeUpdate("UPDATE trainer SET payment_day ='"+y+"' WHERE trainer_id = '"+a+"'");
             JOptionPane.showMessageDialog(null, "successfully","MESSAGE", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "error","MESSAGE", JOptionPane.INFORMATION_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_reActionPerformed

    private void chActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chActionPerformed

        String g=(String) ch.getSelectedItem();
       String uname="root";
       String pass="jobs";
       String con="jdbc:Mysql://localhost:3306/gym";
       Connection  conn=null;
      if(g.equals("All")){  DefaultTableModel model = new DefaultTableModel(new String[]{"Trainer ID","Trainer Name","Sex","Payment_Date","Type"}, 0);
            try {
              
        conn=DriverManager.getConnection(con,uname,pass);
       Statement st=conn.createStatement();
       ResultSet rs=st.executeQuery("select * from trainer");
       while(rs.next()){
            String a = rs.getString("trainer_id");
            String b = rs.getString("trainer_name");
            String c = rs.getString("sex");
            String d = rs.getString("payment_day");
            String e = rs.getString("type");
            model.addRow(new Object[]{a, b, c, d, e});
       }
       table.setModel(model);
                 
        } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(null, "error","MESSAGE", JOptionPane.INFORMATION_MESSAGE);
                Logger.getLogger(equipment.class.getName()).log(Level.SEVERE, null, ex); }}
      else if(g.equals("Shift")){
          DefaultTableModel model = new DefaultTableModel(new String[]{"Trainer ID","Trainer Name","Sex","Payment_Date","Type"}, 0);
            try {
              String s1="shift 1";
              String s2="shift 2";
        conn=DriverManager.getConnection(con,uname,pass);
       Statement st=conn.createStatement();
       ResultSet rs=st.executeQuery("select * from trainer where type ='"+s1+"'");
       while(rs.next()){
            String a = rs.getString("trainer_id");
            String b = rs.getString("trainer_name");
            String c = rs.getString("sex");
            String d = rs.getString("payment_day");
            String e = rs.getString("type");
            model.addRow(new Object[]{a, b, c, d, e});
       }
       table.setModel(model);
                 
        } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(null, "error","MESSAGE", JOptionPane.INFORMATION_MESSAGE);
                Logger.getLogger(equipment.class.getName()).log(Level.SEVERE, null, ex); }}
      else if(g.equals("Regular")){
          DefaultTableModel model = new DefaultTableModel(new String[]{"Trainer ID","Trainer Name","Sex","Payment_Date","Type"}, 0);
            try {
              String s1="Regular";
              
        conn=DriverManager.getConnection(con,uname,pass);
       Statement st=conn.createStatement();
       ResultSet rs=st.executeQuery("select * from trainer where type ='"+s1+"'");
       while(rs.next()){
            String a = rs.getString("trainer_id");
            String b = rs.getString("trainer_name");
            String c = rs.getString("sex");
            String d = rs.getString("payment_day");
            String e = rs.getString("type");
            model.addRow(new Object[]{a, b, c, d, e});
       }
       table.setModel(model);
                 
        } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(null, "error","MESSAGE", JOptionPane.INFORMATION_MESSAGE);
                Logger.getLogger(equipment.class.getName()).log(Level.SEVERE, null, ex); }}
      
        // TODO add your handling code here:
    }//GEN-LAST:event_chActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        new manemp().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void re1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re1ActionPerformed

        new menu().setVisible(true);
          dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_re1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manegemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manegemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manegemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manegemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manegemp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ac;
    private javax.swing.JTextField am;
    private javax.swing.JComboBox<String> ch;
    private javax.swing.JTextField ids;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton re;
    private javax.swing.JButton re1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
