/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gyma;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author JOBS
 */
public class schedule extends javax.swing.JFrame {

    /**
     * Creates new form schedule
     */
    public schedule() {
        initComponents();
          String s="Select pack_name from package";
      // String sa="Select daily_price,monthly_price,3 month from package";
       String uname="root";
       String pass="jobs";
       String con="jdbc:Mysql://localhost:3306/gym";
       Connection  conn=null;
        try {
             conn=DriverManager.getConnection(con,uname,pass);
            Statement st=conn.createStatement();
            ResultSet rs1 = st.executeQuery(s);
             while ((rs1.next())) {
                pack.addItem(rs1.getString(1));  
               }
               st.close();
               rs1.close(); 
               conn.close();
            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        day = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pack = new javax.swing.JComboBox<>();
        ltime = new javax.swing.JLabel();
        lpan = new javax.swing.JLabel();
        nre = new javax.swing.JButton();
        nadd = new javax.swing.JButton();
        sadd = new javax.swing.JButton();
        sre = new javax.swing.JButton();
        lday = new javax.swing.JLabel();
        time = new javax.swing.JTextField();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 100, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(224, 224, 224));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        day.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday" }));
        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });
        jPanel1.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 200, 50));

        jPanel2.setBackground(new java.awt.Color(53, 111, 204));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JOBS\\Documents\\gyma\\src\\images\\Favorites\\icons8-home-50.png")); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 160));

        pack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packActionPerformed(evt);
            }
        });
        jPanel1.add(pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 200, 50));

        ltime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ltime.setText("Time");
        jPanel1.add(ltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 100, 40));

        lpan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lpan.setText("Package");
        jPanel1.add(lpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 120, 40));

        nre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nre.setText("Remove");
        nre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nreActionPerformed(evt);
            }
        });
        jPanel1.add(nre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 40));

        nadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nadd.setText("ADD");
        nadd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(204, 204, 204), null, null));
        nadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naddActionPerformed(evt);
            }
        });
        jPanel1.add(nadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 100, 40));

        sadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sadd.setText("ADD To Sch");
        sadd.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        sadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saddActionPerformed(evt);
            }
        });
        jPanel1.add(sadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 210, 60));

        sre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sre.setText("Remove From");
        sre.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        sre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sreActionPerformed(evt);
            }
        });
        jPanel1.add(sre, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 210, 60));

        lday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lday.setText("Day");
        jPanel1.add(lday, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 100, 40));

        time.setBackground(new java.awt.Color(224, 224, 224));
        time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 200, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed

        
        // TODO add your handling code here:
    }//GEN-LAST:event_dayActionPerformed

    private void packActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packActionPerformed

    private void naddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naddActionPerformed

        sre.setVisible(false);
        sadd.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_naddActionPerformed

    private void nreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nreActionPerformed

        sadd.setVisible(false);

        sre.setVisible(true);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_nreActionPerformed

    private void saddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saddActionPerformed

        Date d = new Date();
        SimpleDateFormat t= new SimpleDateFormat("YYYY-MM-DD");
        t.format(d);
            String a=(String) pack.getSelectedItem();
            String b=(String) day.getSelectedItem();
            String ti=time.getText();
          String uname="root";
       String pass="jobs";
       String con="jdbc:Mysql://localhost:3306/gym";
       Connection  conn=null;
        try {
            conn=DriverManager.getConnection(con,uname,pass);
            Statement stmt=(Statement) conn.createStatement();
            stmt.executeUpdate("UPDATE schedule SET `"+b+"` = '"+a+"' WHERE (`time` = '"+ti+"');");
             JOptionPane.showMessageDialog(null, "successfully","MESSAGE", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "error","MESSAGE", JOptionPane.INFORMATION_MESSAGE);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_saddActionPerformed

    private void sreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sreActionPerformed

             String a=(String) pack.getSelectedItem();
            String b=(String) day.getSelectedItem();
            String ti=time.getText();
          String uname="root";
       String pass="jobs";
       String con="jdbc:Mysql://localhost:3306/gym";
       Connection  conn=null;
        try {
            conn=DriverManager.getConnection(con,uname,pass);
            Statement stmt=(Statement) conn.createStatement();
            stmt.executeUpdate("Delete from schedule where time ='"+ti+"' and '"+b+"' = '"+a+"'");
             JOptionPane.showMessageDialog(null, "successfully","MESSAGE", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "error","MESSAGE", JOptionPane.INFORMATION_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_sreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new menu().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new schedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> day;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lday;
    private javax.swing.JLabel lpan;
    private javax.swing.JLabel ltime;
    private javax.swing.JButton nadd;
    private javax.swing.JButton nre;
    private javax.swing.JComboBox<String> pack;
    private javax.swing.JButton sadd;
    private javax.swing.JButton sre;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
